
# *************************************************
#                     Utilities
# *************************************************
disc.score <- function(x_col, y_col, divs) {
  disc.score <- 0
  for (div in divs) {
    left <- y_col[x_col <= div]
    left.of.div <- ifelse(length(left), min(left), 0.0)
    
    right <- y_col[x_col > div]
    right.of.div <- ifelse(length(right), min(right), 0.0)
    
    disc.score <- disc.score + (left.of.div - right.of.div)
  }
  return(disc.score / length(disc.divs))
}


#' Calculate the discrimination score for each cutoff
#'
#' @param df Data frame containing the score data from a set of 
#'        models generated by Rosetta
#' @param disc.divs RMSD cutoffs to use for .
#' @return A data.frame with the discrimination score for each target in the 
#'         input data.frame.
#' @examples
#' d.scores <- calc.disc.scores(score.data, groups = c("label", "model.type"), 
#'                              divs = c(0.5, 1.0, 1.5, 2.0))
#' @export
calc.disc.scores <- function(df, groups = c("label", "model.type"), 
                                  divs = c(1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 6.0)) {
  # For now 'H3_RMS' and 'scaled.score' are hard-coded
  rms_col <- as.name("H3_RMS")
  score_col <- as.name("scaled.score")
  
  disc.scores <- df %>% 
    group_by_(.dots = groups) %>% 
    dplyr::summarize_(disc.score = interp(~disc.score(x_col_name, y_col_name, 
                                                      divs), 
                                          .values = c(x_col_name = rms_col, 
                                                      y_col_name = score_col)))
  
  disc.scores$disc.score <- format(disc.scores$disc.score, digits = 2)
  return(disc.scores)
}

score.scaling.params <- function(scores) {
  ninety.fifth.percentile <- quantile(scores, 0.95, names = FALSE)
  fifth.percentile <- quantile(scores, 0.05, names = FALSE)
  scale.factor <- 1 / (ninety.fifth.percentile - fifth.percentile)
  return(c("scale.factor" = scale.factor, "fifth.percentile" = fifth.percentile))
}

scale.score <- function(scores) {
  params <- score.scaling.params(scores)
  return((scores - params["fifth.percentile"]) * params["scale.factor"])
}

scale.nat.score <- function(scores, nat.score) {
  params <- score.scaling.params(scores)
  return((nat.score - params["fifth.percentile"]) * params["scale.factor"])
}


#' Scale scores from 1 (95th percentile) to -1 (5th percentile)
#'
#' @param df Data frame containing the score data from a set of 
#'        models generated by Rosetta
#' @param groups a list of strings to group the targets
#' @return A data.frame with the discrimination score for each target in the 
#'         input data.frame.
#' @examples
#' scaled.scores <- scale.scores(score.data, groups = c("label", "model.type"), 
#'                          col.name = "total_score", nat.col = "nat_score")
#' @export
calc.scaled.scores <- function(df, groups = c("label", "model.type"), 
                         col.name = "total_score", nat.col = "nat_score") {

  score.col <- as.name(col.name)
  nat.score.col <- as.name(nat.col)
  
  df <- df %>% 
    group_by_(.dots = groups) %>% 
    dplyr::mutate_(scaled.score = interp(~scale.score(col_name), 
                                         .values = c(col_name = score.col)),
                   scaled.nat.score = interp(~scale.nat.score(col_name, 
                                                              nat_col_name), 
                                             .values = c(col_name = score.col,
                                                         nat_col_name = nat.score.col)))
  return(df)
}
